Update README.md
Minesraft2/Blooket-Cheats pull request #388
Opened 2023-02-08 21:12 UTC by Wilke000

# Changes
**Adds simulate unlock clarity**

2023-02-08 21:14 UTC, VillainsRule4000 requested changes
could use clarity on "what you could open that day"

2023-02-08 21:17 UTC, LeozaCEO2 commented on README.md
>  Make sure you're running it properly (see [How to use](#how-to-use)), if it still doesn't work and other cheats do, then [make an issue](https://github.com/Minesraft2/Blooket-Cheats/issues)
I made an enhancement issue to write only blooks available at the current time can be simulated

2023-02-08 21:19 UTC, VillainsRule4000 commented on README.md
>  Make sure you're running it properly (see [How to use](#how-to-use)), if it still doesn't work and other cheats do, then [make an issue](https://github.com/Minesraft2/Blooket-Cheats/issues)
this pr is because of that issue.

2023-02-08 21:20 UTC, Wilke000 commented
> could use clarity on "what you could open that day"

Done

2023-02-08 21:20 UTC, VillainsRule4000 requested changes
this still doesn't clarify "what you can open that day" - change that language
also mysticals, not mythicals

2023-02-08 21:21 UTC, Wilke000 commented
Got it

2023-02-08 21:25 UTC, VillainsRule4000 approved these changes
I guess this works, Minesraft will likely commit this himself.

2023-02-08 21:36 UTC, Wilke000 commented
K :)

2023-02-09 02:40 UTC, LeozaCEO2 commented
If this doesn't work, which hopefully it will, just make a note that it only allows what is available in the Blooket shop at the the current time

2023-02-09 03:10 UTC, LeozaCEO2 commented on README.md
>  Make sure you're running it properly (see [How to use](#how-to-use)), if it still doesn't work and other cheats do, then [make an issue](https://github.com/Minesraft2/Blooket-Cheats/issues)
yes ik

2023-02-09 20:16 UTC, fowntain approved these changes
I approve of these changes. +1

2023-02-10 13:05 UTC, Wilke000 commented
Fixed typo

2023-02-10 13:44 UTC, LeozaCEO2 approved these changes

2023-02-10 15:42 UTC, Greenlio commented
if he wants to add it, he'll commit it himself. either way, this isn't getting merged.

2023-02-10 15:42 UTC, closed without merging

2023-02-10 15:43 UTC, Wilke000 commented
> if he wants to add it, he'll commit it himself. either way, this isn't getting merged.

why not

2023-02-10 15:44 UTC, Greenlio commented
> > if he wants to add it, he'll commit it himself. either way, this isn't getting merged.
> 
> why not

we don't merge 99% of pull requests because we don't want to add contributors

2023-02-10 15:45 UTC, Wilke000 commented
> > > if he wants to add it, he'll commit it himself. either way, this isn't getting merged.
> > 
> > 
> > why not
> 
> we don't merge 99% of pull requests because we don't want to add contributors

ah ok